name: Evaluate Projects

on:
  push:
    branches:
      - main
  
jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Install scorecard
        run: |
          curl -sSL https://github.com/ossf/scorecard/releases/download/v4.13.1/scorecard_4.13.1_linux_amd64.tar.gz | tar xz -C /tmp && sudo mv /tmp/./scorecard-linux-amd64 /usr/local/bin/scorecard
          chmod +x /usr/local/bin/scorecard

      - name: Run evaluation script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./evaluate.sh
          ./evaluate.sh projects

      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: evaluation-output
          path: results.txt
